### ISSUE TITLE
Line spacing between paragraphs in event descriptions is lost

### ISSUE THREAD

**Issue by marpa** [clas-web/events-vtt#3]
HTML p tags seem to be getting stripped out of event post types... See:
https://exchange.uncc.edu/event/native-tree-winter-identification/

**Comment by marpa** [comment]
I think this bug can be fixed by converting line breaks to p tags. See:
https://codex.wordpress.org/Function_Reference/wpautop

**Comment by rmccal14** [comment]
Wrapped post_content in wpautop() function in singel-event.php
