### ISSUE TITLE
Google Calendar event does not load for two unlikely scenarios

### ISSUE THREAD

**Issue by rmccal14** [clas-web/events-vtt#5]
If a submitted event has the format "start date - end date & end time" or "start day - end time", the Google Calendar "Add to Calendar" link will not load. These are the two most unlikely event formats, but I should add a Google Calendar result for this anyways as a placeholder in case that format is chosen (maybe convert to an all day event if it is difficult to program)

**Comment by rmccal14** [comment]
Fixed in latest commit, now the Google Calendar link will default to midnight if no start time was entered, but an end time was. Scenarios updated [here](https://docs.google.com/document/d/1bS-Nuvbgrx-S6QmtOnNV3-6nuUIbkVS26F0VijUO5FA/edit).

![image](https://user-images.githubusercontent.com/41296669/50248429-07661e00-03a9-11e9-95a0-017205367acc.png)

**Comment by marpa** [comment]
Great you were able to fix this, will look at later. - Alex
